# Generated by Django 5.1.1 on 2024-09-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0001_initial'),
    ]

    operations = [
    ]
