# Generated by Django 5.1.1 on 2024-09-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_app', '0002_auto_20240927_1049'),
    ]

    operations = [
    ]
